{{- if and .Values.rbac.create .Values.rbac.clusterScoped -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "uptime-kuma-operator.fullname" . }}
  labels:
    {{- include "uptime-kuma-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "uptime-kuma-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "uptime-kuma-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
