---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.uptimekuma.io
  resources:
  - uptimekumaconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.uptimekuma.io
  resources:
  - uptimekumaconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.uptimekuma.io
  resources:
  - uptimekumaconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.uptimekuma.io
  resources:
  - uptimekumagroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.uptimekuma.io
  resources:
  - uptimekumagroups/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.uptimekuma.io
  resources:
  - uptimekumagroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.uptimekuma.io
  resources:
  - uptimekumamonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.uptimekuma.io
  resources:
  - uptimekumamonitors/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.uptimekuma.io
  resources:
  - uptimekumamonitors/status
  verbs:
  - get
  - patch
  - update
