# permissions for end users to view uptimekumaconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: uptimekumaconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: uptime-kuma-operator
    app.kubernetes.io/part-of: uptime-kuma-operator
    app.kubernetes.io/managed-by: kustomize
  name: uptimekumaconfig-viewer-role
rules:
- apiGroups:
  - monitoring.uptimekuma.io
  resources:
  - uptimekumaconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.uptimekuma.io
  resources:
  - uptimekumaconfigs/status
  verbs:
  - get
