# permissions for end users to edit uptimekumamonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: uptimekumamonitor-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: uptime-kuma-operator
    app.kubernetes.io/part-of: uptime-kuma-operator
    app.kubernetes.io/managed-by: kustomize
  name: uptimekumamonitor-editor-role
rules:
- apiGroups:
  - monitoring.uptimekuma.io
  resources:
  - uptimekumamonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.uptimekuma.io
  resources:
  - uptimekumamonitors/status
  verbs:
  - get
