apiVersion: monitoring.uptimekuma.io/v1alpha1
kind: UptimeKumaConfig
metadata:
  labels:
    app.kubernetes.io/name: uptimekumaconfig
    app.kubernetes.io/instance: uptimekumaconfig-sample
    app.kubernetes.io/part-of: uptime-kuma-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: uptime-kuma-operator
  name: uptimekumaconfig-sample
spec:
  # TODO(user): Add fields here
